DROP TABLE AUTHOR CASCADE CONSTRAINTS 
;
DROP TABLE BOOKS CASCADE CONSTRAINTS 
;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS 
;
DROP TABLE  CREDIT_CARD_DETAILS CASCADE CONSTRAINTS 
;
DROP TABLE  ORDER_DETAILS CASCADE CONSTRAINTS 
;
DROP TABLE PUBLISHER CASCADE CONSTRAINTS 
;
DROP TABLE PURCHASE_HISTORY CASCADE CONSTRAINTS 
;
DROP TABLE SHIPPING_TYPE CASCADE CONSTRAINTS 
;
DROP TABLE SHOPPING_CART CASCADE CONSTRAINTS 
;DROP SEQUENCE order_id_seq
;
DROP VIEW customer_details;
