-- Execute by using teach_a account

CREATE TABLE t2(a1 NUMBER DEFAULT ON NULL 10 NOT NULL, a2 VARCHAR2(30));
SELECT * FROM t2;
ALTER TABLE t2 ADD(a3 NUMBER DEFAULT ON NULL 20 NOT NULL);
INSERT INTO t2 (a1, a2) VALUES (NULL,'abc');
SELECT * FROM t2;

