-- 2 --
SELECT * FROM dictionary;
SELECT * FROM dict;

SELECT COUNT(*) FROM dict WHERE table_name LIKE 'USER%'; -- 449
SELECT COUNT(*) FROM dict WHERE table_name LIKE 'DBA%'; -- 921

SELECT * FROM user_tables;
SELECT * FROM all_tables;

SELECT * FROM dict WHERE table_name = 'USER_TABLES';
SELECT * FROM dict_columns WHERE table_name = 'USER_TABLES';

SELECT * FROM user_tables;
SELECT * FROM user_tab_columns WHERE table_name = 'EMPLOYEES';

SELECT * FROM user_constraints WHERE table_name = 'EMPLOYEES';
SELECT * FROM user_cons_columns WHERE table_name = 'EMPLOYEES';

SELECT * FROM user_indexes WHERE table_name = 'EMPLOYEES';
SELECT * FROM user_ind_columns WHERE table_name = 'EMPLOYEES';

-- SELECT * FROM dict WHERE table_name LIKE 'USER%PRIV%';

SELECT * FROM user_views;
SELECT * FROM user_sequences;
SELECT * FROM user_synonyms;
SELECT * FROM user_objects;

SELECT * FROM user_tab_comments;
SELECT * FROM user_col_comments WHERE table_name = 'EMPLOYEES';

COMMENT ON TABLE emp1 IS 'Test Constraints Table';
COMMENT ON COLUMN emp1.emp_id IS 'ID Number of the Employee. Primary Key';

SELECT DISTINCT object_type FROM user_objects ORDER BY 1;

-- 3 -- 
CREATE SEQUENCE s1;

CREATE SEQUENCE s2
    START WITH 10
    INCREMENT BY 10
    MAXVALUE 100
    CYCLE
    NOCACHE;
    
SELECT s1.NEXTVAL s1, s2.NEXTVAL s2 FROM dual;
SELECT s1.CURRVAL s1, s2.CURRVAL s2 FROM dual;

SELECT * FROM user_sequences;

ALTER SEQUENCE s2 MINVALUE -100;
SELECT s1.NEXTVAL s1, s2.NEXTVAL s2 FROM dual;
ALTER SEQUENCE s2 MINVALUE 10;
SELECT s1.NEXTVAL s1, s2.NEXTVAL s2 FROM dual;
ALTER SEQUENCE s2 NOCYCLE;
SELECT s1.NEXTVAL s1, s2.NEXTVAL s2 FROM dual;
-- 51,	100
SELECT s1.NEXTVAL s1, s2.NEXTVAL s2 FROM dual;
--ORA-08004: Sequenz S2.NEXTVAL exceeds MAXVALUE und kann nicht abgerufen werden

CREATE SEQUENCE seq1;
CREATE TABLE test_seq(
    id NUMBER DEFAULT seq1.NEXTVAL,
    text VARCHAR2(100)
);

INSERT INTO test_seq VALUES(3, 'T');
INSERT INTO test_seq(text) VALUES('T1');
INSERT INTO test_seq(text) VALUES('T2');
INSERT INTO test_seq(text) VALUES('T3');
INSERT INTO test_seq(text) VALUES('T4');
INSERT INTO test_seq VALUES(NULL, 'T');

SELECT * FROM test_seq;
DROP SEQUENCE seq1;
INSERT INTO test_seq VALUES(NULL, 'T5');
INSERT INTO test_seq VALUES(DEFAULT, 'T6');
--ORA-02289: Sequence ist nicht vorhanden.

-- "Identity_Option" Clause
DROP TABLE test_seq PURGE;
CREATE TABLE test_seq(
    id NUMBER GENERATED ALWAYS AS IDENTITY
    (
        START WITH 10
        INCREMENT BY 10
        MAXVALUE 50
    ),
    text VARCHAR2(100)
);

SELECT * FROM user_tab_columns WHERE table_name = 'TEST_SEQ';
SELECT * FROM user_sequences;

INSERT INTO test_seq VALUES(3, 'T');
--ORA-32795: Wert kann nicht in Identity-Spalte eingefügt werden, die mit GENERATED ALWAYS erstellt wurde
INSERT INTO test_seq VALUES(NULL, 'T');
--ORA-32795: Wert kann nicht in Identity-Spalte eingefügt werden, die mit GENERATED ALWAYS erstellt wurde
INSERT INTO test_seq(text) VALUES('T1');
INSERT INTO test_seq(text) VALUES('T2');
INSERT INTO test_seq(text) VALUES('T3');
INSERT INTO test_seq(text) VALUES('T4');
INSERT INTO test_seq(text) VALUES('T5');
INSERT INTO test_seq(text) VALUES('T6');
--ORA-08004: Sequenz ISEQ$$_94077.NEXTVAL exceeds MAXVALUE und kann nicht abgerufen werden
SELECT * FROM test_seq;

DROP TABLE test_seq PURGE;
CREATE TABLE test_seq(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
    (
        START WITH 10
        INCREMENT BY 10
    ),
    text VARCHAR2(100)
);

INSERT INTO test_seq VALUES(3, 'T');
INSERT INTO test_seq VALUES(NULL, 'T');
--ORA-01400: Einfügen von NULL in ("ORA1"."TEST_SEQ"."ID") nicht möglich
INSERT INTO test_seq(text) VALUES('T1');
INSERT INTO test_seq(text) VALUES('T2');
INSERT INTO test_seq(text) VALUES('T3');
INSERT INTO test_seq VALUES(DEFAULT, 'T4');
INSERT INTO test_seq VALUES(DEFAULT, 'T5');
INSERT INTO test_seq VALUES(DEFAULT, 'T6');

SELECT * FROM test_seq;

DROP TABLE test_seq PURGE;
CREATE TABLE test_seq(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
    (
        START WITH 10
        INCREMENT BY 10
    ),
    text VARCHAR2(100)
);

INSERT INTO test_seq VALUES(3, 'T');
INSERT INTO test_seq VALUES(NULL, 'T');
INSERT INTO test_seq(text) VALUES('T1');
INSERT INTO test_seq(text) VALUES('T2');
INSERT INTO test_seq(text) VALUES('T3');

SELECT * FROM test_seq;
SELECT * FROM user_sequences;
DROP TABLE test_seq PURGE;
SELECT * FROM user_sequences;

CREATE SYNONYM e FOR employees;

SELECT * FROM e;

SELECT * FROM user_synonyms;
SELECT * FROM all_synonyms WHERE synonym_name = 'DUAL';

CREATE TABLE big_table AS SELECT * FROM all_objects;
SELECT COUNT(*) FROM big_table; -- 78316
SELECT * FROM big_table;

SELECT * FROM big_table WHERE object_name = 'EMP1'; -- Cost 371
CREATE INDEX big_table_obj_name_idx ON big_table(object_name);
SELECT * FROM big_table WHERE object_name = 'EMP1'; -- Cost 4
ALTER INDEX big_table_obj_name_idx INVISIBLE;

CREATE INDEX big_table_obj_name_idx1 ON big_table(object_name);
--ORA-01408: Diese Spaltenliste hat bereits einen Index

CREATE BITMAP INDEX big_table_obj_name_idx1 ON big_table(object_name);
SELECT * FROM big_table WHERE object_name = 'EMP1'; -- Cost 1

SELECT * FROM big_table WHERE LOWER(object_name) = 'emp1'; -- Cost 371
CREATE INDEX big_table_obj_name_idx2 ON big_table(LOWER(object_name));
SELECT * FROM user_ind_expressions;
ANALYZE TABLE big_table COMPUTE STATISTICS;
SELECT * FROM big_table WHERE LOWER(object_name) = 'emp1'; -- Cost 4

SELECT * FROM user_indexes WHERE table_name = 'BIG_TABLE';